### ISSUE TITLE
s3へのアクセス権限

### ISSUE THREAD

**Issue by Yasuhiro0312** [monstar-lab/serverless-mecab-neologd#2]
serverless.ymlのiamRoleStatementsにてs3へのアクセス権限を与えないと、tokenizeハンドラー内のs3へアクセスするところで死にます。

```
def prepareMecabDic():
    if not os.path.exists(DICDIR):
        os.mkdir(DICDIR)
    for mdic in MECAB_DIC_FILES:
        dest_dic = DICDIR + mdic
        if not os.path.exists(dest_dic) or os.path.getsize(dest_dic) == 0:
            with open(dest_dic, 'wb') as f:
                s3.download_file(AWS_S3_BUCKET,
                        AWS_S3_DICTIONARY_DIR + '/' + mdic, dest_dic)
```

serverless.ymlに
```

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
      Resource:
        - "*"
```
Resourceをワイルドカードにしていますが、このままはよくないかもですが、s3:GetObjectにて権限与えないといけないのではないでしょうか？
